"use client";

export default function Home() {
  return (
    <div className="overflow-hidden">
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
      <p>hola</p>
    </div>
  );
}
